### ISSUE TITLE
weapon category

### ISSUE THREAD

**Issue by 0xerade** [TheFuckingRat/RatPoison#96] opened 2019-07-23 16:21 UTC
when changing weapon category ratpoison just crashed

Exception in thread "DefaultDispatcher-worker-3" kotlin.KotlinNullPointerException
        at rat.poison.ui.tabs.AimTab$15.invoke(AimTab.kt:350)
        at rat.poison.ui.tabs.AimTab$15.invoke(AimTab.kt:19)
        at rat.poison.ui.UIUtilKt$changed$listener$1.changed(UIUtil.kt:9)
        at com.badlogic.gdx.scenes.scene2d.utils.ChangeListener.handle(ChangeListener.java:28)
        at com.badlogic.gdx.scenes.scene2d.Actor.notify(Actor.java:183)
        at com.badlogic.gdx.scenes.scene2d.Actor.fire(Actor.java:148)
        at com.badlogic.gdx.scenes.scene2d.utils.Selection.fireChangeEvent(Selection.java:218)
        at com.badlogic.gdx.scenes.scene2d.utils.Selection.set(Selection.java:103)
        at com.badlogic.gdx.scenes.scene2d.ui.SelectBox.setSelected(SelectBox.java:271)
        at rat.poison.ui.UIUpdateKt.uiUpdate(UIUpdate.kt:74)
        at rat.poison.ui.tabs.AimTab$10.invoke(AimTab.kt:261)
        at rat.poison.ui.tabs.AimTab$10.invoke(AimTab.kt:19)
        at rat.poison.ui.UIUtilKt$changed$listener$1.changed(UIUtil.kt:9)
        at com.badlogic.gdx.scenes.scene2d.utils.ChangeListener.handle(ChangeListener.java:28)
        at com.badlogic.gdx.scenes.scene2d.Actor.notify(Actor.java:183)
        at com.badlogic.gdx.scenes.scene2d.Actor.fire(Actor.java:148)
        at com.badlogic.gdx.scenes.scene2d.utils.Selection.fireChangeEvent(Selection.java:218)
        at com.badlogic.gdx.scenes.scene2d.utils.Selection.clear(Selection.java:198)
        at com.badlogic.gdx.scenes.scene2d.ui.SelectBox.clearItems(SelectBox.java:162)
        at rat.poison.ui.tabs.AimTab$9.invoke(AimTab.kt:235)
        at rat.poison.ui.tabs.AimTab$9.invoke(AimTab.kt:19)
        at rat.poison.ui.UIUtilKt$changed$listener$1.changed(UIUtil.kt:9)
        at com.badlogic.gdx.scenes.scene2d.utils.ChangeListener.handle(ChangeListener.java:28)
        at com.badlogic.gdx.scenes.scene2d.Actor.notify(Actor.java:183)
        at com.badlogic.gdx.scenes.scene2d.Actor.fire(Actor.java:148)
        at com.badlogic.gdx.scenes.scene2d.utils.Selection.fireChangeEvent(Selection.java:218)
        at com.badlogic.gdx.scenes.scene2d.utils.Selection.choose(Selection.java:52)
        at com.badlogic.gdx.scenes.scene2d.utils.ArraySelection.choose(ArraySelection.java:24)
        at com.badlogic.gdx.scenes.scene2d.ui.SelectBox$SelectBoxList$2.clicked(SelectBox.java:375)
        at com.badlogic.gdx.scenes.scene2d.utils.ClickListener.touchUp(ClickListener.java:88)
        at com.badlogic.gdx.scenes.scene2d.InputListener.handle(InputListener.java:59)
        at com.badlogic.gdx.scenes.scene2d.Stage.touchUp(Stage.java:350)
        at com.badlogic.gdx.InputMultiplexer.touchUp(InputMultiplexer.java:124)
        at com.badlogic.gdx.InputEventQueue.drain(InputEventQueue.java:86)
        at com.badlogic.gdx.backends.lwjgl3.Lwjgl3Input.update(Lwjgl3Input.java:178)
        at com.badlogic.gdx.backends.lwjgl3.Lwjgl3Window.update(Lwjgl3Window.java:390)
        at com.badlogic.gdx.backends.lwjgl3.Lwjgl3Application.loop(Lwjgl3Application.java:137)
        at com.badlogic.gdx.backends.lwjgl3.Lwjgl3Application.<init>(Lwjgl3Application.java:111)
        at rat.poison.RatPoison$main$1.invokeSuspend(RatPoison.kt:144)
        at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
        at kotlinx.coroutines.DispatchedTask.run(Dispatched.kt:233)
        at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:594)
        at kotlinx.coroutines.scheduling.CoroutineScheduler.access$runSafely(CoroutineScheduler.kt:60)
        at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:742)

**Comment by TheFuckingRat** [comment] 2019-07-30 20:22
Send a cfg that causes the crash? It's working fine for me.

**Comment by TheFuckingRat** [comment] 2019-08-05 22:36
I couldn't reproduce any error, so I'm closing this issue.

**Closed by TheFuckingRat** 2019-08-05 22:36 UTC
