### ISSUE TITLE
Issued too many commands to the server

### ISSUE THREAD

**Issue by duxaquan** [TheFuckingRat/RatPoison#517] opened 2020-07-16 18:51 UTC
Doesn't really matter what version I use (1.5 > 1.7), after about a minute I get disconnected with the error 'Issued too many commands to the server' with the console error: Disconnect: #GameUI_Disconnect_TooManyCommands.

RP console shows no errors.

**Comment by matt1tk** [comment] 2020-07-16 20:10
Default config?

**Comment by duxaquan** [comment] 2020-07-16 20:38
> Default config?

Yes. Also rebuilt it a couple of times with the different version.

**Comment by duxaquan** [comment] 2020-07-17 01:02
Tried a few more times. Worked without issues for almost 2 full maps and started again after around 2 hours of play. About every minute.

**Comment by matt1tk** [comment] 2020-07-17 01:24
Duplicate of #154

**Comment by matt1tk** [comment] 2020-07-17 18:49
Is your issue fixed by #154 ?

**Closed** 2020-07-22 15:22 UTC
